## Project
name: end_2_end_demo
version: "1.0"
config-vesion: 1
profile: end_2_end_demo

## Sources
model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]


## Models
models:
  end_2_end_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
