end_2_end_demo: 
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SF_INTELLIGENCE_DEMO
      database: SF_AI_Demo
      schema: dev
      warehouse: Snow_Intelligence_demo_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SF_INTELLIGENCE_DEMO
      database: SF_AI_Demo
      schema: demo_schema
      warehouse: Snow_Intelligence_demo_wh