dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SF_DBT_DEMO
      database: SF_dbt_Demo
      schema: dev
      warehouse: SF_dbt_Demo_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SF_DBT_DEMO
      database: SF_dbt_Demo
      schema: prod
      warehouse: SF_dbt_Demo_wh